[build]
  publish = "."
  functions = "netlify/functions"

# Route the frontend call to the serverless function
[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200
  force = true
